# Generated by Django 4.0.2 on 2022-02-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=30),
        ),
    ]
