# Generated by Django 4.0.2 on 2022-04-20 14:26

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newuser_followedby_newuser_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='profile_picture',
            field=models.ImageField(default='posts/default.png', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
