# Generated by Django 4.0.2 on 2022-02-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='status',
            field=models.CharField(choices=[('showcase', 'Showcase'), ('purchased', 'Purchased'), ('available', 'Available')], default='available', max_length=10),
        ),
    ]
