# Generated by Django 4.0.2 on 2022-02-25 05:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_alter_art_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
