# Generated by Django 4.0.2 on 2022-03-08 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0005_alter_art_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='likes',
            field=models.ManyToManyField(related_name='art_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
