# Generated by Django 4.0.2 on 2022-03-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_art_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='likes',
        ),
    ]
