# Generated by Django 4.0.2 on 2022-03-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
