# Generated by Django 4.0.2 on 2022-03-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0012_alter_art_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='genre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
