# Generated by Django 4.0.2 on 2022-03-18 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0014_alter_art_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmark_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
