# Generated by Django 4.0.2 on 2022-03-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0015_art_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='bookmarks',
        ),
    ]
