# Generated by Django 4.0.2 on 2022-04-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0017_art_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='genre',
            field=models.CharField(choices=[('abstract', 'Abstract'), ('pop', 'Pop'), ('realism', 'Realism'), ('potrait', 'Potrait'), ('landscape', 'Landscape'), ('mithila', 'Mithila')], default='abstract', max_length=20, null=True),
        ),
    ]
