# Generated by Django 4.0.2 on 2022-04-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0018_alter_art_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
